### ISSUE TITLE
properly initialize repos "from scratch" 

### ISSUE THREAD

**Issue by mukil** [digitalmemex/bootstrap#2]
Installing repositories from scratch, as described at the bottom of this page (http://digitalmemex.github.io/devs.html), misses to set the "Repository Status" to "Installed".

This has consequences for the repository-manager and the app-developer trying to access its new repo/source code.

See original bug description at https://github.com/digitalmemex/repository-manager/issues/6

**Comment by mukil** [comment]
Initializing repo "from scratch" == empty "Repository URI" > missing origin > following stacktrace:

<pre>
2015-03-17 23:02:17,340 INFO  DmxBootstrapPlugin               request application repository-manager index
2015-03-17 23:02:17,341 INFO  DmxBootstrapPlugin               repository request repository-manager topic
2015-03-17 23:02:18,407 INFO  DmxBootstrapPlugin               clone request singlepage-require
2015-03-17 23:02:18,407 INFO  DmxBootstrapPlugin               repository request singlepage-require topic
2015-03-17 23:02:18,410 WARN  DmxBootstrapPlugin               the cloning of singlepage-require has failed
org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
    at org.digitalmemex.bootstrap.DmxBootstrapPlugin.cloneRepository(DmxBootstrapPlugin.java:145)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.6.0_34]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.6.0_34]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.6.0_34]
    at java.lang.reflect.Method.invoke(Method.java:622)[:1.6.0_34]
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350)[77:com.sun.jersey.jersey-server:1.14.0]
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)[78:com.sun.jersey.servlet:1.14.0]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)[78:com.sun.jersey.servlet:1.14.0]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)[78:com.sun.jersey.servlet:1.14.0]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[53:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[68:org.ops4j.pax.web.pax-web-jetty:3.1.2]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[68:org.ops4j.pax.web.pax-web-jetty:3.1.2]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:77)[68:org.ops4j.pax.web.pax-web-jetty:3.1.2]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.Server.handle(Server.java:370)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[59:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
    at java.lang.Thread.run(Thread.java:701)[:1.6.0_34]
</pre>

**Comment by mukil** [comment]
So, the cycle would need be as follows (supporting all current modes envisoned by you):
- "Repository Status" > "Downloaded" means folder in '/filrepo/dmx' was created: This can happen either a) via clone and git or via b) creating a "Repository" manually (webclient or repository-manager-u) > **"Install" button shows up** in repo-manager-ui
- Clickin on "Install" repistory in repo-manager sets the "Repository Status" > "Installed" and thus > **"Open app" shows up**.

Making it comfortable:
- *_Creating a new repository_ (as soon as it is supported by repository-manager ui) "from scratch" (as you say) should do both (download/create folder and install the repo-topic) - so the app-developer could just say "open app"
